[project]
name = "pygoban"
version = "0.1.0"
description = "Just another Go Board/ SGF Reader"
authors = [{ name = "Tim Heithecker", email = "tim.heithecker@gmail.com" }]

dependencies = ["pyqt6", "PyQt6-Graphs>=6.8.0", "PyQt6-Charts>=6.8.0"]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = ["coverage", "pytest", "pytest-mock>=3.12.0"]

[tool.pytest]
testpaths = "tests"

[tool.pylint.MAIN]
init-hook = """
import pylint_venv
pylint_venv.inithook()
"""
[tool.pylint.format]
max-line-length = 100
[tool.pylint."messages control"]
disable = [
  "raw-checker-failed",
  "bad-inline-option",
  "locally-disabled",
  "file-ignored",
  "suppressed-message",
  "useless-suppression",
  "deprecated-pragma",
  "use-symbolic-message-instead",
  "use-implicit-booleaness-not-comparison-to-string",
  "use-implicit-booleaness-not-comparison-to-zero",
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",

]

[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.tox
    | \.venv
    | _build
    | build
    | dist
  )/
  | migrations
  | \.mypy_cache
)
'''

[tool.isort]
profile = "black"


[tool.pdm]
distribution = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
